---
name: Run all tests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    name: Run tests for Python ${{ matrix.python-version }}
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: make test
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: src/.reports/**/junit*.xml
      - name: Archive test and coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: test-and-coverage-report
          path: src/.reports
